Repository 101-Coconsulting/TC3005B.501-Frontend, pull requests merged in 2025-05, with the labels that each got.

#53 10 sub task requests list design content tables
  src/components/DataTable.astro
  src/components/TableFallback.astro
  src/components/TableHeader.astro
  src/components/TableRow.astro
Labels: enhancement

#79 docs: translate `README.md`
  README.md
Labels: documentation, chore

#77 76 task getting started instructions
  README.md
Labels: documentation, chore

#81 Implement display of autorizaciones, atenciones and comprobacio…
  src/components/DataTable.astro
  src/components/History.tsx
  src/components/RequestsLists/AuthRequestsList.tsx
  src/components/Table/DataTable.tsx
  src/components/Table/Pagination.tsx
  src/components/Table/TableFallback.astro
  src/components/Table/TableHeader.tsx
  src/components/Table/TableRow.tsx
  src/components/TableFallback.astro
  src/components/TableHeader.astro
  src/components/TableRow.astro
  src/pages/atenciones.astro
  src/pages/autorizaciones.astro
  src/pages/comprobaciones.astro
Labels: enhancement

#85 62 applicant allow editing of travel request
  src/data/get-user-request-2.json
  src/data/get-user-request.json
  src/data/get-user-requests-2.json
  src/pages/crear-solicitud.astro
  src/pages/editar-solicitud/[id].astro
  src/types/menu-config.ts
  src/views/ApplicantView.astro
Labels: bug, enhancement

#101 Release PR v0.2.0
  CHANGELOG.md
  README.md
  package.json
  src/components/Button.tsx
  src/components/DataTable.astro
  src/components/History.tsx
  src/components/Modal.tsx
  src/components/ModalWrapper.tsx
  src/components/RequestActions.tsx
  src/components/RequestApproval.astro
  src/components/RequestAttention.astro
  src/components/RequestBudgeting.astro
  src/components/RequestDetail.astro
  src/components/RequestDraft.astro
  src/components/RequestsLists/AuthRequestsList.tsx
  src/components/Table/DataTable.tsx
  src/components/Table/Pagination.tsx
  src/components/Table/TableFallback.astro
  src/components/Table/TableHeader.tsx
  src/components/Table/TableRow.tsx
  src/components/TableFallback.astro
  src/components/TableHeader.astro
  src/components/TableRow.astro
  src/data/get-user-request-2.json
  src/data/get-user-request.json
  src/data/get-user-requests-2.json
  src/pages/atenciones.astro
  src/pages/autorizaciones.astro
  src/pages/cotizaciones.astro
  src/pages/crear-solicitud.astro
  src/pages/detalles-solicitud/[id].astro
  src/pages/editar-solicitud/[id].astro
  src/pages/perfil-usuario.astro
  src/pages/solicitudes-draft.astro
  src/types/menu-config.ts
  src/views/ApplicantView.astro
Labels: documentation, enhancement, release

#72 feat(pages): add Reimbursements Panel with balance tracking and reque…
  src/pages/reembolso.astro
Labels: enhancement

#120 feat: implement travel request form submission with backend integration
  src/components/CreateTravelRequestForm.tsx
  src/pages/crear-solicitud.astro
Labels: chore
